apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/jcapellansosa/local-stack.git
    targetRevision: main
    path: platform/keycloak/manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: keycloak
  syncPolicy:
    managedNamespaceMetadata:
      labels:
        istio-injection: enabled
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
